# Generated by Django 5.0.1 on 2024-02-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
    ]
