# Generated by Django 5.0.1 on 2024-02-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_applypackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='package_images/')),
            ],
        ),
    ]
